users/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django import forms
from django.utils.translation import ugettext_lazy as __
from django.utils.translation import ugettext as _
from django.contrib.auth.forms import AuthenticationForm as DjangoAuthForm
from django.contrib.auth.models import Group
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import SetPasswordForm
from django.utils import timezone


class AuthenticationForm(DjangoAuthForm):
    """
    Base class for authenticating users. Extend this to get a form that accepts
    username/password logins.
    """
    username = forms.CharField(label=__("Username"))


def get_user_form(modelclass):
    class UserForm(forms.ModelForm):
        email = forms.EmailField(required=True, label=_('Email'))
        first_name = forms.CharField(required=True, max_length=255, label=_('First name'))
        last_name = forms.CharField(required=True, max_length=255, label=_('Last name'))
        groups = forms.ModelMultipleChoiceField(queryset=Group.objects.all(), label=_('Groups'), required=False)

        class Meta:
            model = modelclass
            fields = ['email']

    return UserForm


def get_password_reset_form(password_reset_confirm_urlname, ConcreteUserModel):
    class CustomPasswordResetForm(PasswordResetForm):

        def save(self, domain_override=None,
                 subject_template_name='registration/password_reset_subject.txt',
                 email_template_name='registration/password_reset_email.html',
                 extra_email_context=None,
                 use_https=False, token_generator=default_token_generator,
                 from_email=None, request=None, html_email_template_name=None):
            """
            Generates a one-use only link for resetting password and sends to the
            user.
            """
            # TODO: remove? -> unused; or pass as extra_context kwarg to confirm_account
            if not extra_email_context:
                extra_email_context = dict()

            email = self.cleaned_data["email"]
            active_users = ConcreteUserModel._default_manager.filter(
                email__iexact=email, is_active=True)

            for user in active_users:

                # Make sure that no email is sent to a user that actually has
                # a password marked as unusable
                if not user.has_usable_password():
                    # send account activation email as the user obviously did not confirm his account yet
                    user.confirm_account(subject=_('Reset password'))
                else:
                    # send password reset
                    user.confirm_account(template=email_template_name, subject=_('Reset password'))

        def clean_email(self):
            # UserModel = get_user_model()
            active_users = ConcreteUserModel._default_manager.filter(email__iexact=self.cleaned_data['email'], is_active=True)

            if not len(active_users):
                raise forms.ValidationError('Zu dieser E-Mail-Adresse existiert kein aktiver Account.')
            else:
                return self.cleaned_data['email']

    return CustomPasswordResetForm


class AccountActivationPasswordForm(SetPasswordForm):

    def save(self, *args, **kwargs):
        if self.user.activation_timestamp is None:
            # only set the activation ts when the user is created!
            self.user.activation_timestamp = timezone.now()
        return super().save(*args, **kwargs)

users/templates/users/accounts/account_confirm.html
{% extends "users/accounts/base.html" %}
{% load i18n %}

{% block title %}{% trans 'Activate your Account' %}{% endblock %}

{% block bodyclass %}account-process{% endblock %}

{% block content %}
    {% if validlink %}
            <h1>{% trans 'Activate your account and set your password' %}</h1>

            <p>{% trans "Please enter the password twice so we can verify you typed it in correctly." %}</p>

            <form action="" method="post">{% csrf_token %}
                <div class="form-row">
                    {{ form.new_password1.errors }}
                    <label for="id_new_password1">{% trans 'New password:' %}</label>
                    {{ form.new_password1 }}
                </div>
                <div class="form-row">
                    {{ form.new_password2.errors }}
                    <label for="id_new_password2">{% trans 'Confirm password:' %}</label>{{ form.new_password2 }}
                    
                    <input type="submit" value="{% trans 'Activate your account' %}" />
                </div>
            </form>

    {% else %}
            <h1>{% trans 'Account activation unsuccessful' %}</h1>
            <p>{% trans "The Account activation link was invalid, possibly because it has already been used." %}</p>
    {% endif %}

{% endblock %}

users/templates/users/accounts/account_confirm_complete.html
{% extends "users/accounts/base.html" %}
{% load i18n %}

{% block title %}{% trans "Account successfuly confirmed" %}{% endblock %}
{% block bodyclass %}account-process{% endblock %}
{% block content %}

        <h1>{% trans 'Your account has been successfuly confirmed' %}</h1>
        <br/>
        <div class="buttons mega"><a href="{{ login_url }}" >{% trans 'Log in with your new account' %}</a></div>

{% endblock %}

users/templates/users/accounts/base.html
{% extends "users/accounts/base_site.html" %}

users/templates/users/accounts/base_site.html
{% load i18n %}
<!DOCTYPE html >
<html>
	<head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <title>{% block title %} {% endblock %}</title>
        
        {% include "media_includes.html" %}
	</head>
	<body class="users {% block bodyclass %} {% endblock %}">
	
	    <div id="container">
            <div id="header">
                <div id="branding">
                    {% block branding%}<a id="logo"></a>{% endblock %}
                </div>
            </div>
            <div id="content">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

users/templates/users/accounts/logged_out.html
{% extends "users/accounts/base.html" %}
{% load i18n %}

{% block title %}{% trans "Login" %}{% endblock %}

{% block content %}
<div class="note">
    <p>{% trans "Thanks for spending some quality time with the application today." %}</p>
    <p><a href="../">{% trans 'Log in again' %}</a></p>
</div>

{% endblock %}

users/templates/users/accounts/login.html
{% extends "users/accounts/base.html" %}
{% load i18n %}

{% block title %}{% trans "Login" %}{% endblock %}

{% block bodyclass %}login{% endblock %}

{% block branding %}<h1>{% trans "Login" %}</h1> {% endblock %}

{% block content %}
      
        <form action="{{ login_url }}" method="post" id="login-form">{% csrf_token %}
        
            {% if form.errors and not form.non_field_errors and not form.this_is_the_login_form.errors %}
            <p class="errornote">
            {% blocktrans count form.errors.items|length as counter %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktrans %}
            </p>
            {% endif %}
            {{ form.this_is_the_login_form.errors }}
           
            {% for error in form.non_field_errors %}
            <p class="errornote">
                {{ error }}
            </p>
            {% endfor %}
        
          <div class="form-row {% if form.username.errors %}error{% endif %}">
            {% if not form.this_is_the_login_form.errors %}{#{ form.username.errors }#}{% endif %}
            <label for="id_username" class="required">{% trans 'Username:' %}</label> {{ form.username }}
          </div>
          <div class="form-row {% if form.password.errors %}error{% endif %} password" >
            {% if not form.this_is_the_login_form.errors %}{#{ form.password.errors }#}{% endif %}
            <label for="id_password" class="required">{% trans 'Password:' %}</label> {{ form.password }}
            <input type="hidden" name="this_is_the_login_form" value="1" />
            <input type="hidden" name="next" value="{{ next }}" />
            
          </div>
          <div class="submit-row">
            <input type="submit" value="{% trans 'Log in' %}" />
             <a href="{{ password_reset_url }}" class="forgot_password">{% trans "Forgot your password?" %}</a>
          </div>
        </form>
       
        
        <script type="text/javascript">
        document.getElementById('id_username').focus()
        $('#login-form').submit(function() {
            var u = $('input[name="username"]')
            u.val(u.toLowerCase())
        })
        </script>
{% endblock %}

users/templates/users/accounts/password_change.html
{% extends "users/accounts/base.html" %}
{% load i18n %}
{% load i18n static %}




{% block title %}{% trans 'Password change' %}{% endblock %}

{% block content %}<div id="content-main">

<form action="" method="post">{% csrf_token %}
<div>
{% if form.errors %}
    <p class="errornote">
    {% blocktrans count counter=form.errors.items|length %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktrans %}
    </p>
{% endif %}

<h1>{% trans 'Password change' %}</h1>

<p>{% trans "Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}</p>

<fieldset class="module aligned wide">

<div class="form-row">
    {{ form.old_password.errors }}
    <label for="id_old_password" class="required">{% trans 'Old password' %}:</label>{{ form.old_password }}
</div>

<div class="form-row">
    {{ form.new_password1.errors }}
    <label for="id_new_password1" class="required">{% trans 'New password' %}:</label>{{ form.new_password1 }}
</div>

<div class="form-row">
{{ form.new_password2.errors }}
    <label for="id_new_password2" class="required">{% trans 'Password (again)' %}:</label>{{ form.new_password2 }}
</div>

</fieldset>

<div class="submit-row">
    <input type="submit" value="{% trans 'Change my password' %}" class="default" />
</div>

<script type="text/javascript">document.getElementById("id_old_password").focus();</script>
</div>
</form></div>

{% endblock %}

users/templates/users/accounts/password_change_done.html
{% extends "users/accounts/base.html" %}
{% load i18n %}


{% block title %}{% trans 'Password change successful' %}{% endblock %}

{% block content %}

<h1>{% trans 'Password change successful' %}</h1>

<p>{% trans 'Your password was changed.' %}</p>

{% endblock %}

users/templates/users/accounts/password_reset.html
{% extends "users/accounts/base.html" %}
{% load i18n %}

{% block title %}{% trans "Password reset" %}{% endblock %}

{% block bodyclass %}account-process{% endblock %}


{% block content %}

    <h1>{% trans "Password reset" %}</h1>

    <p>{% trans "Forgotten your password? Enter your e-mail address below, and we'll e-mail instructions for setting a new one." %}</p>
    <form action=""  method="post">
        {% csrf_token %}
        {{ form.email.errors }}
        <div class="form-row {% if form.email.errors %} error {% endif %}">
            <label for="id_email">{% trans 'E-mail address:' %}</label> 
            {{ form.email }} 
            <input type="submit" value="{% trans 'Reset my password' %}" />
        </div>
    </form> 
{% endblock %}

users/templates/users/accounts/password_reset_complete.html
{% extends "users/accounts/base.html" %}
{% load i18n %}

{% block title %}{% trans "Password reset" %}{% endblock %}
{% block bodyclass %}account-process{% endblock %}
{% block content %}



        <h1>{% trans 'Password reset complete' %}</h1>

        <p>{% trans "Your password has been set.  You may go ahead and log in now." %}</p>

        <div class="buttons mega"><a href="{{ login_url }}">{% trans 'Log in' %}</a></div>

{% endblock %}

users/templates/users/accounts/password_reset_confirm.html
{% extends "users/accounts/base.html" %}
{% load i18n %}

{% block title %}{% trans "Password reset" %}{% endblock %}
{% block bodyclass %}account-process{% endblock %}

{% block content %}


        {% if validlink %}
        <h1>{% trans 'Enter new password' %}</h1>

        <p>{% trans "Please enter your new password twice so we can verify you typed it in correctly." %}</p>

        <form action="" method="post">{% csrf_token %}
            {{ form.new_password1.errors }}
            <div class="form-row">
                <label for="id_new_password1">{% trans 'New password:' %}</label>{{ form.new_password1 }}
            </div>
            {{ form.new_password2.errors }}
            <div class="form-row">
                <label for="id_new_password2">{% trans 'Confirm password:' %}</label>
                {{ form.new_password2 }}
                <input type="submit" value="{% trans 'Change my password' %}" />
            </div>
       </form>

        {% else %}

        <h1>{% trans 'Password reset unsuccessful' %}</h1>

        <p>{% trans "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>
        
        {% endif %}


{% endblock %}

users/templates/users/accounts/password_reset_done.html
{% extends "users/accounts/base.html" %}
{% load i18n %}

{% block title %}{% trans 'Password reset' %}{% endblock %}

{% block bodyclass %}account-process{% endblock %}

{% block content %}

        <h1>{% trans 'Password reset successful' %}</h1>
        <p>{% trans "We've e-mailed you instructions for setting your password to the e-mail address you submitted. You should be receiving it shortly." %}</p>

{% endblock %}